FROM node:lts-alpine3.16

WORKDIR /usr/src/app
COPY ./api/package*.json ./api/
COPY ./api/src ./api/src
WORKDIR /usr/src/app/api

CMD npm config set cache-min 9999999 && \
    npm install && \
    npm run start:dev
